language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
